# Generated by Django 3.2.14 on 2022-08-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogmodel',
            table='bolog',
        ),
    ]
