# Generated by Django 3.2.14 on 2022-08-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subject_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科', 'verbose_name_plural': '学科'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
