# Generated by Django 3.2.14 on 2022-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220803_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='is_hot',
            field=models.BooleanField(null=True, verbose_name='是否热门'),
        ),
    ]
