# Generated by Django 3.2.16 on 2023-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_subject_is_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=40)),
                ('create_time', models.BigIntegerField(default=1673603954.2959592)),
            ],
            options={
                'db_table': 'privacy_policy_history',
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth',
            field=models.IntegerField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(max_length=255, verbose_name='照片'),
        ),
    ]
